# Generated by Django 5.2.11 on 2026-02-16 08:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'associations',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='CNMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_super_admin', models.BooleanField(default=False, help_text='Accès admin Django')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cn_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cn_members',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif')], default='ACTIVE', max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poles', to='core.department')),
            ],
            options={
                'db_table': 'poles',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('max_capacity', models.IntegerField(default=1, help_text='Nombre max de jeunes simultanés')),
                ('disponibilite_reelle', models.IntegerField(default=1, help_text='Places disponibles actuellement')),
                ('is_active', models.BooleanField(default=True)),
                ('is_trained', models.BooleanField(default=False, help_text='Formation validée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='core.association')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to=settings.AUTH_USER_MODEL)),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='core.pole')),
            ],
            options={
                'db_table': 'mentors',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='association',
            name='pole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associations', to='core.pole'),
        ),
        migrations.CreateModel(
            name='Animateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('is_coordinator', models.BooleanField(default=False, help_text='True = ACP (Coordinateur), False = AP')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='animateur', to=settings.AUTH_USER_MODEL)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animateurs', to='core.association')),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animateurs', to='core.pole')),
            ],
            options={
                'db_table': 'animateurs',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='YoungRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Garçon'), ('F', 'Fille'), ('O', 'Autre')], max_length=1)),
                ('city', models.CharField(max_length=100)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'Nouvelle'), ('PENDING', 'En attente de mentor'), ('ASSIGNED', 'Mentor assigné'), ('CLOSED', 'Clôturée'), ('CANCELLED', 'Annulée')], default='NEW', max_length=20)),
                ('needs_description', models.TextField(help_text='Description des besoins du jeune')),
                ('urgency_level', models.IntegerField(default=1, help_text='1-5, 5 = très urgent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='young_requests', to='core.association')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
                ('pole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='young_requests', to='core.pole')),
            ],
            options={
                'db_table': 'young_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mentorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateField(blank=True, help_text='Date effective de début', null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACTIVE', 'Actif'), ('CLOSED', 'Clôturé'), ('ABORTED', 'Abandonné')], default='PENDING', max_length=20)),
                ('closure_reason', models.TextField(blank=True)),
                ('alerte_rouge', models.BooleanField(default=False, help_text='Problème signalé')),
                ('dernier_contact', models.DateField(blank=True, null=True)),
                ('notes_suivi', models.TextField(blank=True, help_text="Notes de l'AP")),
                ('ap_responsable', models.ForeignKey(blank=True, help_text='AP chargé du suivi de ce mentorat', limit_choices_to={'is_coordinator': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentorats_suivis', to='core.animateur')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorats', to='core.mentor')),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorats', to='core.pole')),
                ('young_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentorat', to='core.youngrequest')),
            ],
            options={
                'db_table': 'mentorats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_score', models.IntegerField(default=0, help_text='Score de matching IA (0-100)')),
                ('overridden', models.BooleanField(default=False, help_text='True si humain a outrepassé IA')),
                ('justification', models.TextField(blank=True, help_text='Raison de la décision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matching_decisions_taken', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_decisions', to='core.mentor')),
                ('young_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_decisions', to='core.youngrequest')),
            ],
            options={
                'db_table': 'matching_decisions',
                'ordering': ['-created_at'],
            },
        ),
    ]
