# Generated by Django 5.2.11 on 2026-02-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pole',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
