# Generated by Django 5.2.11 on 2026-02-20 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mentor_city_mentor_department'),
        ('core', '0004_add_suivi_mentorat'),
    ]

    operations = [
    ]
