# Generated by Django 5.2.11 on 2026-02-27 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20260220_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du financeur')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('type', models.CharField(choices=[('local', 'Local'), ('national', 'National')], max_length=10, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Financement',
                'verbose_name_plural': 'Financements',
                'db_table': 'financements',
                'ordering': ['nom'],
            },
        ),
        migrations.RemoveField(
            model_name='association',
            name='pole',
        ),
        migrations.RemoveField(
            model_name='pole',
            name='main_department',
        ),
        migrations.RemoveField(
            model_name='youngrequest',
            name='association',
        ),
        migrations.AddField(
            model_name='pole',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='poles', to='core.department', verbose_name='Départements couverts'),
        ),
        migrations.AddField(
            model_name='youngrequest',
            name='diplome_prepare',
            field=models.CharField(blank=True, choices=[('CAP', 'Niveau 3 — CAP'), ('BEP', 'Niveau 3 — BEP'), ('BAC_PRO', 'Niveau 4 — Bac Pro'), ('BAC_AUTRE', 'Niveau 4 — Bac autres'), ('BP', 'Niveau 4 — BP'), ('BTS', 'Niveau 5 — BTS'), ('DUT', 'Niveau 5 — DUT'), ('LIC_PRO', 'Niveau 6 — Licence Pro'), ('BUT', 'Niveau 6 — BUT'), ('MASTER', 'Niveau 7 — Master'), ('DEA', 'Niveau 7 — DEA'), ('DES', "Niveau 7 — Diplôme d'études spécialisées"), ('ING', 'Niveau 7 — Ingénieur')], max_length=20, verbose_name='Diplôme préparé'),
        ),
        migrations.AddField(
            model_name='youngrequest',
            name='nom_etablissement',
            field=models.CharField(blank=True, help_text='Nom saisi librement par le jeune lors de sa demande', max_length=200, verbose_name="Nom de l'établissement"),
        ),
        migrations.AddField(
            model_name='youngrequest',
            name='situation',
            field=models.CharField(blank=True, choices=[('apprentissage', 'Déjà en apprentissage'), ('recherche', "En recherche d'apprentissage")], max_length=20, verbose_name='Situation'),
        ),
        migrations.AlterField(
            model_name='youngrequest',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='youngrequest',
            name='needs_description',
            field=models.TextField(verbose_name='Description des besoins'),
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'établissement")),
                ('code_postal', models.CharField(max_length=10, verbose_name='Code postal')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etablissements', to='core.pole', verbose_name='Pôle')),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissements',
                'db_table': 'etablissements',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='youngrequest',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='young_requests', to='core.etablissement', verbose_name="Établissement (validé par l'ACP)"),
        ),
        migrations.CreateModel(
            name='MentoratFinancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_specifique', models.CharField(blank=True, help_text='Référence interne du financement pour ce mentorat', max_length=100, verbose_name='Code dossier/contrat')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('financement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorat_financements', to='core.financement')),
                ('mentorat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financements', to='core.mentorat')),
            ],
            options={
                'verbose_name': 'Financement de mentorat',
                'verbose_name_plural': 'Financements de mentorats',
                'db_table': 'mentorat_financements',
                'unique_together': {('mentorat', 'financement')},
            },
        ),
    ]
