# Generated by Django 5.2.11 on 2026-02-27 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cnmember_add_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnmember',
            name='fonction',
            field=models.CharField(blank=True, choices=[('membre', 'Membre CN'), ('resp_anim', 'Responsable Animation du Comite'), ('resp_reseau', 'Responsable Animation du Reseau des Poles'), ('resp_doc', 'Responsable Doc Internes - Formation'), ('resp_finance', 'Responsable Finance/Financements/Achats'), ('resp_com', 'Responsable Com (yc TSB) - Partenariats'), ('resp_si', "Responsable des Systemes d'Information (SI)")], default='membre', max_length=20),
        ),
        migrations.AlterField(
            model_name='cnmember',
            name='is_super_admin',
            field=models.BooleanField(default=False, help_text='Acces admin Django'),
        ),
        migrations.AlterField(
            model_name='cnmember',
            name='pole',
            field=models.ForeignKey(blank=True, help_text='Pole de rattachement (si ACP / AP)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cn_members', to='core.pole'),
        ),
    ]
