# Generated by Django 5.2.11 on 2026-03-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_mentorat_cloture_en_attente_evaluation_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnmember',
            name='cn_acces_complet',
            field=models.BooleanField(default=False, help_text='Acces complet CN : gestion mentors, poles, animateurs, configuration'),
        ),
    ]
