# Generated by Django 5.2.11 on 2026-03-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_cn_acces_complet'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='commune',
            field=models.CharField(blank=True, max_length=200, verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='youngrequest',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='youngrequest',
            name='commune',
            field=models.CharField(blank=True, max_length=200, verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='youngrequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='youngrequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='youngrequest',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
