# Generated by Django 5.2.11 on 2026-03-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_geo_coords_to_mentor_and_youngrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='training_date',
            field=models.DateField(blank=True, help_text='Date à laquelle le mentor a validé sa formation ORA', null=True, verbose_name='Date de formation'),
        ),
    ]
