# Generated by Django 5.2.11 on 2026-03-31 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_training_date_to_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatureMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_postal', models.CharField(max_length=10, verbose_name='Code postal')),
                ('commune', models.CharField(blank=True, max_length=200, verbose_name='Commune')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('experience_pro', models.TextField(verbose_name='Expérience professionnelle')),
                ('domaines', models.JSONField(default=list, verbose_name="Domaines d'expertise")),
                ('disponibilite', models.CharField(blank=True, max_length=50, verbose_name='Disponibilité')),
                ('motivation', models.TextField(blank=True, verbose_name='Motivation')),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('VALIDATED', 'Validée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=20)),
                ('notes_rejet', models.TextField(blank=True, verbose_name='Motif de rejet')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_mentors', to='core.association', verbose_name='Association choisie')),
                ('mentor_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidature_source', to='core.mentor', verbose_name='Mentor créé')),
                ('pole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_mentors', to='core.pole', verbose_name='Pôle détecté')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_validees', to='core.animateur', verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Candidature Mentor',
                'verbose_name_plural': 'Candidatures Mentors',
                'db_table': 'candidatures_mentors',
                'ordering': ['-created_at'],
            },
        ),
    ]
