# Generated by Django 5.2.11 on 2026-03-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_candidature_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('subject', models.CharField(choices=[('apprentice', 'Je suis apprenti(e)'), ('mentor', 'Je veux devenir mentor'), ('partner', 'Partenariat'), ('press', 'Presse / Média'), ('other', 'Autre')], max_length=50, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
