# Generated by Django 5.2.11 on 2026-05-29 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_animateur_is_acp_is_ap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorat',
            name='ap_responsable',
            field=models.ForeignKey(blank=True, help_text='Animateur chargé du suivi (AP ou ACP)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentorats_suivis', to='core.animateur'),
        ),
    ]
