# Generated by Django 5.2.11 on 2026-05-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_urgency_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='observations',
            field=models.TextField(blank=True, default='', verbose_name="Particularité pour l'affectation"),
        ),
    ]
