# Generated by Django 5.2.11 on 2026-05-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_mentor_observations_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorat',
            name='closure_reason_code',
            field=models.CharField(blank=True, choices=[('NO_CONTACT', 'Aucun vrai contact établi'), ('LOST_CONTACT', 'Perte définitive du contact'), ('DIPLOMA_FAIL', 'Échec diplôme'), ('MENTEE_STOP', 'Arrêt souhaité par le mentoré'), ('OBJECTIVE_REACHED', 'Objectif atteint')], max_length=20, verbose_name='Raison de clôture'),
        ),
        migrations.AddField(
            model_name='mentorat',
            name='nb_heures',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name="Nombre d'heures de suivi"),
        ),
        migrations.AddField(
            model_name='mentorat',
            name='nb_rencontres',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de rencontres'),
        ),
        migrations.AddField(
            model_name='mentorat',
            name='objectif_mentor',
            field=models.TextField(blank=True, verbose_name='Objectif du mentor'),
        ),
        migrations.AlterField(
            model_name='mentorat',
            name='notes_suivi',
            field=models.TextField(blank=True, help_text="Bilan de l'AP sur le déroulement du mentorat", verbose_name='Bilan sommaire du suivi'),
        ),
        migrations.AlterField(
            model_name='mentorat',
            name='problematiques',
            field=models.JSONField(blank=True, default=list, help_text='Liste de codes parmi les problématiques prédéfinies'),
        ),
    ]
