# Generated by Django 5.2.3 on 2026-07-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_evaluation_mentor_3_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='youngrequest',
            name='date_previsionnelle',
            field=models.DateField(blank=True, help_text="Si en apprentissage : date prévisionnelle d'obtention du diplôme. Si en recherche : date prévisionnelle de début de formation.", null=True, verbose_name='Date prévisionnelle'),
        ),
    ]
