# Generated by Django 5.2.3 on 2026-09-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_youngrequest_date_previsionnelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorat',
            name='closure_reason_code',
            field=models.CharField(blank=True, choices=[('NO_CONTACT', 'Aucun vrai contact établi'), ('LOST_CONTACT', 'Perte définitive du contact'), ('DIPLOMA_FAIL', 'Échec diplôme'), ('MENTEE_STOP', 'Arrêt souhaité par le mentoré'), ('OBJECTIVE_REACHED', 'Objectif atteint'), ('OTHER', 'Autre')], max_length=20, verbose_name='Raison de clôture'),
        ),
    ]
