# Generated by Django 5.2.3 on 2026-09-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_mentorat_closure_reason_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='youngrequest',
            name='raison_refus',
            field=models.TextField(blank=True, default='', help_text="Motif saisi par l'AP/APC qui a refusé cette demande", verbose_name='Raison du refus'),
        ),
    ]
