# Generated by Django 5.2.3 on 2026-09-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_youngrequest_raison_refus'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorat',
            name='cloture_date_demandee',
            field=models.DateField(blank=True, help_text="Date de clôture proposée par le mentor (modifiable par l'AP/APC avant confirmation)", null=True),
        ),
    ]
