# Generated by Django 5.2.3 on 2026-09-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_mentorat_cloture_date_demandee'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorat',
            name='cloture_demandee_at',
            field=models.DateTimeField(blank=True, help_text="Horodatage de la demande de clôture du mentor (pour afficher le délai d'attente à l'AP/APC)", null=True),
        ),
    ]
