# Generated by Django 5.2.3 on 2026-09-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_mentorat_cloture_demandee_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Désactivation définitive : la fiche a été anonymisée à cette date', null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='archived_original_data',
            field=models.JSONField(blank=True, help_text='Snapshot des données personnelles avant anonymisation (restauration CN/admin uniquement)', null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='archived_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
