# Generated by Django 5.2.3 on 2026-10-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_animateur_archivage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorat',
            name='closure_reason_code',
            field=models.CharField(blank=True, choices=[('NO_CONTACT', 'Aucun vrai contact établi'), ('LOST_CONTACT', 'Perte définitive du contact'), ('DIPLOMA_FAIL', 'Échec diplôme'), ('MENTEE_STOP', 'Arrêt souhaité par le mentoré'), ('OBJECTIVE_REACHED', 'Objectif atteint'), ('OTHER', 'Autre motif satisfaisant'), ('OTHER_NEGATIVE', 'Autre motif insatisfaisant')], max_length=20, verbose_name='Raison de clôture'),
        ),
    ]
