# Generated by Django 5.2.3 on 2026-10-02 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='pole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.pole'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='pole_name',
            field=models.CharField(blank=True, help_text="Code/nom du pôle au moment de l'action (conservé même si le pôle change ou est supprimé)", max_length=100),
        ),
    ]
